ALTER TABLE "CalendarEvent" ADD COLUMN IF NOT EXISTS "isTrip" BOOLEAN DEFAULT false;
ALTER TABLE "CalendarEvent" ADD COLUMN IF NOT EXISTS "destination" TEXT;
ALTER TABLE "CalendarEvent" ADD COLUMN IF NOT EXISTS "startDate" TEXT;
ALTER TABLE "CalendarEvent" ADD COLUMN IF NOT EXISTS "endDate" TEXT;
ALTER TABLE "CalendarEvent" ADD COLUMN IF NOT EXISTS "selectedClothes" TEXT[] DEFAULT '{}';

ALTER TABLE "CalendarEvent" ALTER COLUMN "date" DROP NOT NULL;